import type { StaticCaseBlueprintConfig } from "../engine/adapterBuilder.js";
import { SOURCE_TYPE } from "../engine/constants.js";

export const case01BlueprintConfig: StaticCaseBlueprintConfig = {
  closureCatalog: {
    suspect_ids: ["char_sharif"],
    method_ids: ["method_arson_office_origin", "method_side_door_lock", "method_arson_front_door"],
  },
  openableSources: [
    "INT-SHARIF-01",
    "INT-LAYLA-01",
    "INT-HATEM-01",
    "INT-ABU-KHALED-01",
    "TIMELINE-BOARD",
    "CHIEF-DESK",
  ],
  blueprints: {
    review: [
      {
        source_ref: "SCN-03",
        source_type: SOURCE_TYPE.REPORT,
        interaction_id: "ORIGIN-CONFIRMED",
        required_result: "office_origin_confirmed",
        verifies_evidence: true,
      },
      {
        source_ref: "SCN-04",
        source_type: SOURCE_TYPE.REPORT,
        interaction_id: "OUTER-HANDLE",
        required_result: "outer_lock_possible",
        verifies_evidence: true,
      },
      {
        source_ref: "DB-01",
        source_type: SOURCE_TYPE.DOCUMENT,
        interaction_id: "SHIFT-KEY-LOG",
        required_result: "shift_key_assigned_to_sharif",
        verifies_evidence: true,
      },
      {
        source_ref: "DB-03",
        source_type: SOURCE_TYPE.DOCUMENT,
        interaction_id: "PURCHASE-RECEIPT",
        required_result: "thinner_purchase_confirmed",
        verifies_evidence: true,
      },
      {
        source_ref: "DB-06",
        source_type: SOURCE_TYPE.DOCUMENT,
        interaction_id: "TRIP-TRACE",
        required_result: "layla_execution_window_broken",
        verifies_evidence: true,
      },
      {
        source_ref: "EVID-SUP-CCTV-CORRUPTION",
        source_type: SOURCE_TYPE.REPORT,
        interaction_id: "OPEN",
        required_result: "corruption_precedes_heat",
        verifies_evidence: true,
      },
      {
        source_ref: "DB-07",
        source_type: SOURCE_TYPE.DOCUMENT,
        interaction_id: "OPEN",
        required_result: "gps_records_reviewed",
        verifies_evidence: true,
      },
      {
        source_ref: "DB-08",
        source_type: SOURCE_TYPE.DOCUMENT,
        interaction_id: "OPEN",
        required_result: "financial_records_reviewed",
        verifies_evidence: true,
      },
      {
        source_ref: "DB-09",
        source_type: SOURCE_TYPE.DOCUMENT,
        interaction_id: "OPEN",
        required_result: "locksmith_records_reviewed",
        verifies_evidence: true,
      },
      {
        source_ref: "DB-05",
        source_type: SOURCE_TYPE.DOCUMENT,
        interaction_id: "OPEN",
        required_result: "coffee_receipt_reviewed",
        verifies_evidence: true,
      },
      {
        source_ref: "EVID-PARTIAL-LOCK",
        source_type: SOURCE_TYPE.OBJECT,
        interaction_id: "OPEN",
        required_result: "partial_lock_reviewed",
        verifies_evidence: true,
      },
      {
        source_ref: "EVID-PARTIAL-FALSE-ORIGIN-STORY",
        source_type: SOURCE_TYPE.STATEMENT,
        interaction_id: "OPEN",
        required_result: "false_origin_story_reviewed",
        verifies_evidence: true,
      },
      {
        source_ref: "EVID-PARTIAL-BLACK-LEDGER",
        source_type: SOURCE_TYPE.STATEMENT,
        interaction_id: "OPEN",
        required_result: "black_ledger_statement_reviewed",
        verifies_evidence: true,
      },
      {
        source_ref: "SCN-05",
        source_type: SOURCE_TYPE.REPORT,
        interaction_id: "OPEN",
        required_result: "chemical_analysis_reviewed",
        verifies_evidence: true,
      },
    ],
    inspect: [
      {
        source_ref: "OBJ-01",
        source_type: SOURCE_TYPE.OBJECT,
        interaction_id: "INSPECT",
        required_result: "black_ledger_fragments_found",
        verifies_evidence: true,
      },
      {
        source_ref: "OBJ-02",
        source_type: SOURCE_TYPE.OBJECT,
        interaction_id: "INSPECT",
        required_result: "spare_key_found",
        verifies_evidence: true,
      },
    ],
    dialog: [
      {
        source_ref: "INT-SHARIF-01",
        interaction_id: "Q03",
        required_result: "preemptive_origin_claim_logged",
        display_text: "أنا قلت المخزن لأن أي حريق غالبًا بيبدأ من الكهربا... ماكنتش أقصد إني أعرف التفاصيل قبل التقرير.",
      },
      {
        source_ref: "INT-SHARIF-01",
        interaction_id: "Q06",
        required_result: "key_access_statement_recorded",
        display_text: "المفتاح الجانبي كان مع عمي، ومعايا نسخة شغل للطوارئ أحيانًا... بس ده شيء طبيعي في الإدارة.",
      },
      {
        source_ref: "INT-LAYLA-01",
        interaction_id: "Q02",
        required_result: "layla_office_entry_logged",
        display_text: "أيوه فتحت المكتب بسرعة قبل ما أمشي. كنت بدور على أوراق خاصة ببابا ثم خرجت فورًا.",
      },
      {
        source_ref: "INT-SHARIF-01",
        interaction_id: "Q09",
        required_result: "ledger_slip_logged",
        display_text: "دفتر إيه؟ أنا... أقصد دفاتر الحسابات العادية. أكيد كان فيه ورق كتير في المكتب.",
      },
      {
        source_ref: "CHIEF-DESK",
        interaction_id: "REQ-EVIDENCE-01",
        required_result: "additional_files_dispatched",
        display_text: "تم توجيه الدعم الفني لإرسال الملفات الإضافية من مسرح الجريمة إلى أرشيف القضية.",
      },
    ],
    timeline: [
      {
        id: "LOCK-EVENT-03",
        interaction_id: "LOCK-EVENT-03",
        required_result: "sharif_near_side_door_confirmed",
        title: "تأكيد وجود شريف (20:41)",
        prerequisites: ["SCN-04", "DB-01"],
      },
      {
        id: "LOCK-EVENT-05",
        interaction_id: "LOCK-EVENT-05",
        required_result: "sharif_no_visual_access_to_origin",
        title: "رؤية شريف المزعومة (21:05)",
        prerequisites: ["SCN-03", "INT-SHARIF-01"],
      },
      {
        id: "LOCK-EVENT-06",
        interaction_id: "LOCK-EVENT-06",
        required_result: "corruption_near_ignition_window",
        title: "فساد الكاميرا (21:01)",
        prerequisites: ["DB-01", "EVID-SUP-CCTV-CORRUPTION"],
      },
    ],
  },
  exactSourceTypes: {
    "TIMELINE-BOARD": SOURCE_TYPE.TIMELINE,
  },
  prefixSourceTypes: [
    { prefix: "INT-", source_type: SOURCE_TYPE.INTERROGATION },
    { prefix: "SCN-", source_type: SOURCE_TYPE.REPORT },
    { prefix: "DIG-", source_type: SOURCE_TYPE.REPORT },
    { prefix: "EVID-", source_type: SOURCE_TYPE.REPORT },
    { prefix: "DB-", source_type: SOURCE_TYPE.DOCUMENT },
    { prefix: "OBJ-", source_type: SOURCE_TYPE.OBJECT },
  ],
  fallbackSourceType: SOURCE_TYPE.SOURCE,
};
